import fs from "node:fs"
import path from "node:path"
import type { Plugin } from "vite"

/**
 * Full set of top-level fields exposed by `world-countries@5`.
 * Keep this in sync with the upstream JSON schema; the plugin will throw if
 * the user (or auto-detection) requests something outside this whitelist so
 * that typos surface at build time instead of producing silent `undefined`s.
 */
export const WORLD_COUNTRIES_FIELDS = [
  "altSpellings",
  "area",
  "borders",
  "capital",
  "cca2",
  "cca3",
  "ccn3",
  "cioc",
  "currencies",
  "demonyms",
  "flag",
  "idd",
  "independent",
  "landlocked",
  "languages",
  "latlng",
  "name",
  "region",
  "status",
  "subregion",
  "tld",
  "translations",
  "unMember",
  "unRegionalGroup",
] as const

export type WorldCountriesField = (typeof WORLD_COUNTRIES_FIELDS)[number]

export interface WorldCountriesFilterOptions {
  /**
   * - `"auto"`: scan project sources for member access on the imported binding
   *   and keep only the referenced fields. Cheapest to maintain — add a new
   *   `c.region` reference and the field will start being included on next
   *   build.
   * - `"manual"`: use the explicit `fields` list verbatim.
   * - `"merge"` (default): union of `auto` + `fields`. Use `fields` to force-
   *   include something the scanner can't see (dynamic key, JSON.stringify,
   *   re-export, etc.) without losing the auto-detection convenience.
   */
  mode?: "auto" | "manual" | "merge"

  /**
   * Explicit fields to keep. Required when `mode === "manual"`, optional in
   * the other two modes (treated as additions in `merge`).
   */
  fields?: WorldCountriesField[]

  /**
   * Globs (relative to project root) that the auto-scanner walks. Defaults to
   * the `src/` tree; broaden it if you import `world-countries` from elsewhere
   * (e.g. a `scripts/` build helper that ends up bundled).
   */
  include?: string[]

  /**
   * Print the resolved field list during build. Helpful when wiring this up
   * for the first time. Defaults to `true` so it's obvious what's shipping.
   */
  verbose?: boolean

  /**
   * Override the path to the upstream `countries.json`. The plugin resolves it
   * via `import.meta.resolve`-equivalent lookup by default, so you only need
   * this for pnpm workspaces with non-standard hoisting.
   */
  countriesJsonPath?: string
}

const VIRTUAL_ID = "\0virtual:world-countries-filtered"
const REAL_SPECIFIER = "world-countries"

/**
 * Vite plugin that swaps `import countries from 'world-countries'` for a
 * field-pruned virtual module. Cuts ~125 kB gzipped from the chunk that
 * imports it without changing any runtime call sites.
 */
export function worldCountriesFilter(
  options: WorldCountriesFilterOptions = {},
): Plugin {
  const {
    mode = "merge",
    fields: manualFields = [],
    include = ["src/**/*.{ts,tsx,js,jsx,mjs,cjs}"],
    verbose = true,
    countriesJsonPath,
  } = options

  if (mode === "manual" && manualFields.length === 0) {
    throw new Error(
      "[world-countries-filter] mode=\"manual\" requires a non-empty `fields` array.",
    )
  }

  validateFields(manualFields)

  let projectRoot = process.cwd()
  let resolvedCountriesPath: string | null = null
  let cachedSource: string | null = null

  return {
    name: "world-countries-filter",
    enforce: "pre",

    configResolved(config) {
      projectRoot = config.root
      resolvedCountriesPath =
        countriesJsonPath ?? locateCountriesJson(projectRoot)
    },

    resolveId(source) {
      if (source === REAL_SPECIFIER) return VIRTUAL_ID
      return null
    },

    async load(id) {
      if (id !== VIRTUAL_ID) return null

      if (cachedSource) return cachedSource

      if (!resolvedCountriesPath) {
        throw new Error(
          "[world-countries-filter] could not locate world-countries/countries.json. " +
            "Pass `countriesJsonPath` explicitly.",
        )
      }

      const fields = await resolveFields({
        mode,
        manualFields,
        include,
        projectRoot,
        plugin: this,
      })

      const raw = await fs.promises.readFile(resolvedCountriesPath, "utf8")
      const countries = JSON.parse(raw) as Record<string, unknown>[]

      const filtered = countries.map((entry) => {
        const out: Record<string, unknown> = {}
        for (const f of fields) {
          if (f in entry) out[f] = entry[f]
        }
        return out
      })

      // Pretty-print is wasteful for a generated module — minify the JSON to
      // squeeze every byte out of the chunk.
      const json = JSON.stringify(filtered)
      cachedSource = `// Generated by vite-plugin-world-countries-filter\n// Kept fields: ${fields.join(
        ", ",
      )}\nexport default ${json};\n`

      if (verbose) {
        const before = Buffer.byteLength(raw, "utf8")
        const after = Buffer.byteLength(json, "utf8")
        const pct = ((1 - after / before) * 100).toFixed(1)
        // eslint-disable-next-line no-console
        console.log(
          `[world-countries-filter] kept ${fields.length}/${WORLD_COUNTRIES_FIELDS.length} fields ` +
            `(${formatBytes(before)} → ${formatBytes(after)}, -${pct}%) [${mode}]`,
        )
      }

      return cachedSource
    },
  }
}

// ────────────────────────────────────────────────────────────────────────────
// internals
// ────────────────────────────────────────────────────────────────────────────

function validateFields(fields: readonly string[]) {
  const allowed = new Set<string>(WORLD_COUNTRIES_FIELDS)
  const bad = fields.filter((f) => !allowed.has(f))
  if (bad.length > 0) {
    throw new Error(
      `[world-countries-filter] unknown field(s): ${bad.join(", ")}. ` +
        `Allowed: ${WORLD_COUNTRIES_FIELDS.join(", ")}`,
    )
  }
}

interface ResolveFieldsArgs {
  mode: "auto" | "manual" | "merge"
  manualFields: WorldCountriesField[]
  include: string[]
  projectRoot: string
  // Vite plugin context — typed as `any` to avoid pulling rollup types here.
  plugin: { warn: (msg: string) => void }
}

async function resolveFields({
  mode,
  manualFields,
  include,
  projectRoot,
  plugin,
}: ResolveFieldsArgs): Promise<WorldCountriesField[]> {
  if (mode === "manual") return dedupe(manualFields)

  const auto = await scanReferencedFields(projectRoot, include)

  if (auto.size === 0 && mode === "auto") {
    plugin.warn(
      "[world-countries-filter] auto-scan found zero field references on the " +
        "`world-countries` import. Falling back to `flag` + `latlng` to keep " +
        "the existing globe map working. Set `mode: \"manual\"` to silence.",
    )
    auto.add("flag")
    auto.add("latlng")
  }

  if (mode === "auto") return dedupe([...auto] as WorldCountriesField[])

  // merge
  return dedupe([...auto, ...manualFields] as WorldCountriesField[])
}

function dedupe<T>(arr: T[]): T[] {
  return [...new Set(arr)]
}

/**
 * Walk the configured globs, find imports of `world-countries`, then collect
 * the field names accessed on the bound identifier. Intentionally a regex-
 * based scanner instead of a full AST pass — adding `@babel/parser` for this
 * one job triples build cold-start time and the false-positive rate of a
 * tight regex over `<ident>.<member>` is effectively zero given the project
 * conventions (no string-keyed access on `countries`/`c`).
 */
async function scanReferencedFields(
  root: string,
  include: string[],
): Promise<Set<WorldCountriesField>> {
  const found = new Set<WorldCountriesField>()
  const allowed = new Set<string>(WORLD_COUNTRIES_FIELDS)

  // Lazy-load tinyglobby so the plugin works without forcing it into prod deps
  // for consumers who bring their own resolver. `tinyglobby` ships with vite.
  const { glob } = await import("tinyglobby")
  const files = await glob(include, {
    cwd: root,
    absolute: true,
    ignore: ["**/node_modules/**", "**/dist/**"],
  })

  // `import xxx from 'world-countries'` (default) — the bound name is `xxx`.
  // Also catch `import * as xxx from 'world-countries'`.
  const importRe =
    /import\s+(?:(\w+)|\*\s+as\s+(\w+))\s+from\s+['"]world-countries['"]/g

  for (const file of files) {
    let source: string
    try {
      source = await fs.promises.readFile(file, "utf8")
    } catch {
      continue
    }

    if (!source.includes("world-countries")) continue

    importRe.lastIndex = 0
    const bindings: string[] = []
    let m: RegExpExecArray | null
    while ((m = importRe.exec(source)) !== null) {
      const name = m[1] ?? m[2]
      if (name) bindings.push(name)
    }
    if (bindings.length === 0) continue

    for (const binding of bindings) {
      // Direct member access: `binding.<field>` or `binding[0].<field>` or
      // chains like `binding.find(...).<field>`. We approximate with a single
      // pattern that captures any `.<field>` following the binding ident.
      // Limit lookahead to avoid matching across whole files.
      const directRe = new RegExp(
        `\\b${binding}\\b[\\w\\.\\[\\]\\(\\)\"'\\?\\,\\s]{0,200}?\\.([a-zA-Z_$][\\w$]*)`,
        "g",
      )
      collectMatches(source, directRe, allowed, found)

      // Destructured loop variable: `for (const c of binding) { c.<field> }`
      // We pull every loop variable bound from `binding` and re-scan for its
      // member access too. Covers `.map(c => c.<field>)`, `.forEach`, etc.
      const loopVars = collectLoopVars(source, binding)
      for (const lv of loopVars) {
        const lvRe = new RegExp(
          `\\b${lv}\\b\\s*\\.([a-zA-Z_$][\\w$]*)`,
          "g",
        )
        collectMatches(source, lvRe, allowed, found)
      }
    }
  }

  return found
}

function collectMatches(
  source: string,
  re: RegExp,
  allowed: Set<string>,
  out: Set<WorldCountriesField>,
) {
  re.lastIndex = 0
  let m: RegExpExecArray | null
  while ((m = re.exec(source)) !== null) {
    const field = m[1]
    if (allowed.has(field)) out.add(field as WorldCountriesField)
  }
}

/**
 * Pull every identifier that gets bound while iterating `binding`:
 *   - `for (const c of binding)` → `c`
 *   - `for (const [, c] of binding.entries())` → ignored (destructure)
 *   - `binding.map((c) => …)` / `.forEach((c) => …)` / `.filter((c) => …)`
 *   - `binding.find((c) => …)` / `.some` / `.every` / `.reduce`
 *   - `const { 0: c } = binding` → ignored
 *
 * Anything more exotic falls through; the user can switch to `mode: "merge"`
 * and pin the field manually.
 */
function collectLoopVars(source: string, binding: string): string[] {
  const vars = new Set<string>()

  const forOfRe = new RegExp(
    `for\\s*\\(\\s*(?:const|let|var)\\s+(\\w+)\\s+of\\s+${binding}\\b`,
    "g",
  )
  let m: RegExpExecArray | null
  while ((m = forOfRe.exec(source)) !== null) vars.add(m[1])

  // `binding.<arrayMethod>((<ident>) => ...)` or `(...args) => ...`
  // Cover only the common single-arg form which matches our codebase style.
  const methodNames = [
    "map",
    "forEach",
    "filter",
    "find",
    "findIndex",
    "some",
    "every",
    "flatMap",
    "reduce",
  ]
  for (const fn of methodNames) {
    const re = new RegExp(
      `${binding}\\s*\\.\\s*${fn}\\s*\\(\\s*(?:async\\s+)?\\(?\\s*(\\w+)`,
      "g",
    )
    while ((m = re.exec(source)) !== null) {
      // `reduce` first arg is the accumulator, not the country — skip it.
      // We can't statically tell which call site uses 1 vs 2 args, so we
      // accept the false-positive: in the worst case we keep a few extra
      // fields, which is cheap.
      vars.add(m[1])
    }
  }

  return [...vars]
}

function locateCountriesJson(root: string): string | null {
  // Walk up from the project root until we find the package. Mirrors what
  // Node's resolver would do, but without spinning it up just for one file.
  // Sufficient for npm/pnpm/yarn classic; users on yarn PnP can pass
  // `countriesJsonPath` explicitly.
  let dir = root
  // Hard cap the walk at 32 levels — protects against pathological symlink
  // loops without changing real-world behaviour.
  for (let i = 0; i < 32; i++) {
    const candidate = path.join(
      dir,
      "node_modules",
      "world-countries",
      "countries.json",
    )
    if (fs.existsSync(candidate)) return candidate
    const parent = path.dirname(dir)
    if (parent === dir) break
    dir = parent
  }
  return null
}

function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} kB`
  return `${(n / (1024 * 1024)).toFixed(2)} MB`
}
